dist: bin
project_name: capi2argo-cluster-operator
env:
  - DOCKER_REPO="ghcr.io/dntosas"
builds:
  - env:
      - CGO_ENABLED=0
    binary: "{{ .ProjectName }}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -mod=vendor
    ldflags:
      - -s -w
      - -X {{ .ProjectName }}/cmd.Version=dev
      - -X {{ .ProjectName }}/cmd.CommitHash={{ .FullCommit }}
    main: .

dockers:
  # amd64
  - image_templates:
      - ghcr.io/dntosas/{{ .ProjectName }}:dev-amd64
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
    - "--pull"
    - "--platform=linux/amd64"
  # arm64
  - image_templates:
      - ghcr.io/dntosas/{{ .ProjectName }}:dev-arm64
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm64/v8"

docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: ghcr.io/dntosas/{{ .ProjectName }}:dev
    image_templates:
      - ghcr.io/dntosas/{{ .ProjectName }}:dev-amd64
      - ghcr.io/dntosas/{{ .ProjectName }}:dev-arm64

release:
  disable: true